version: "3.7"

services:
  db:
    build: "./backend/db"
    image: db-fx-financas-image
    restart: always
    container_name: db-fx-financas-container
    env_file:
      - ./backend/db/db.env
    networks:
      - fx-financas-network
    volumes:
      - ./backend/db/data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  backend:
    build: "./backend"
    restart: always
    image: api-fx-financas-image
    container_name: api-fx-financas-container
    env_file:
      - ./backend/.env.prod
    volumes:
      - ./backend:/home/node/app
      - ./backend/uploads/usuarios:/dist/uploads/usuarios
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - fx-financas-network

  frontend:
    build: "./frontend-vite"
    container_name: frontend-fx-financas-container
    image: front-fx-financas-image
    restart: always
    volumes:
      - ./frontend-vite/nginx:/usr/share/nginx/html
      - ./frontend-vite/nginx:/nginx.config /etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    environment:
      - NGINX_HOST=fluxos.com
      - NGINX_PORT=80
    depends_on:
      - db
      - backend
    networks:
      - fx-financas-network
networks:
  fx-financas-network:
