name: CI-CD
on:
  push:
    branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Generate image docker e-commerceget
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            joaog545/ecommerce-get:${{github.run_number}}
            joaog545/ecommerce-get:lastest
          build-args: VERBOSE=1  # Enable verbose logging if supported by the action

         
